language: php
php:
  - "5.5"
  - "5.4"
  - hhvm

before_script:
  - php composer.phar install
  - chmod 777 travis.phpunit.xml

script:
  - cd $TRAVIS_BUILD_DIR;
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - vendor/bin/phpunit -c $TRAVIS_BUILD_DIR/travis.phpunit.xml
  - php vendor/bin/coveralls -v
